name: hackathon_google
description: "A Flutter project for Google hackathon."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.0
  easy_localization: ^3.0.8
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/translations/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
    - family: Nata_Sans
      fonts:
        - asset: assets/fonts/NataSans/NataSans-Regular.ttf
        - asset: assets/fonts/NataSans/NataSans-Bold.ttf
        - asset: assets/fonts/NataSans/NataSans-Light.ttf
  uses-material-design: true
