// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrbYTXYuFlteAllqhe1eeuWp-O9tjYeCg',
    appId: '1:916644738390:web:52e2d088df7841d18192f7',
    messagingSenderId: '916644738390',
    projectId: 'hackathon-77483',
    authDomain: 'hackathon-77483.firebaseapp.com',
    storageBucket: 'hackathon-77483.firebasestorage.app',
    measurementId: 'G-4Y28Q30R1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwD8fbJLPY9zMX0zLMzezHkOjMEWSvlho',
    appId: '1:916644738390:android:07234e0ec4bab93c8192f7',
    messagingSenderId: '916644738390',
    projectId: 'hackathon-77483',
    storageBucket: 'hackathon-77483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUSWaSObNIcfeB2ocnk-1BANMGC1-XovA',
    appId: '1:916644738390:ios:9c42b431cd3036838192f7',
    messagingSenderId: '916644738390',
    projectId: 'hackathon-77483',
    storageBucket: 'hackathon-77483.firebasestorage.app',
    iosBundleId: 'com.example.hackathonGoogle',
  );
}
